create table if not exists public.head_office_performance (
  id bigint generated by default as identity primary key,
  month text not null check (month ~ '^[0-9]{4}-[0-9]{2}$'),
  user_id uuid not null references public.profiles(id) on delete cascade,
  store_name text not null,
  as_of_date date not null,
  metrics jsonb not null default '{}'::jsonb,
  vas_review jsonb not null default '{}'::jsonb,
  note text,
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month,user_id)
);

create index if not exists head_office_performance_month_idx on public.head_office_performance(month);
create index if not exists head_office_performance_user_idx on public.head_office_performance(user_id);

alter table public.head_office_performance enable row level security;
grant select, insert, update, delete on public.head_office_performance to authenticated;
grant usage, select on sequence public.head_office_performance_id_seq to authenticated;

create policy head_office_performance_admin_select on public.head_office_performance
for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));

create policy head_office_performance_admin_insert on public.head_office_performance
for insert to authenticated
with check (
  exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin')
  and updated_by=(select auth.uid())
);

create policy head_office_performance_admin_update on public.head_office_performance
for update to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'))
with check (
  exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin')
  and updated_by=(select auth.uid())
);

create policy head_office_performance_admin_delete on public.head_office_performance
for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));

create table if not exists public.head_office_store_performance (
  id bigint generated by default as identity primary key,
  month text not null check (month ~ '^[0-9]{4}-[0-9]{2}$'),
  store_name text not null,
  as_of_date date not null,
  metrics jsonb not null default '{}'::jsonb,
  vas_review jsonb not null default '{}'::jsonb,
  note text,
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month,store_name)
);

create index if not exists head_office_store_performance_month_idx on public.head_office_store_performance(month);
alter table public.head_office_store_performance enable row level security;
grant select,insert,update,delete on public.head_office_store_performance to authenticated;
grant usage,select on sequence public.head_office_store_performance_id_seq to authenticated;

create policy head_office_store_performance_admin_select on public.head_office_store_performance
for select to authenticated
using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));

create policy head_office_store_performance_admin_insert on public.head_office_store_performance
for insert to authenticated
with check (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin') and updated_by=(select auth.uid()));

create policy head_office_store_performance_admin_update on public.head_office_store_performance
for update to authenticated
using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin') and updated_by=(select auth.uid()));

create policy head_office_store_performance_admin_delete on public.head_office_store_performance
for delete to authenticated
using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));
