import {test,expect} from '@playwright/test';
for(const width of [320,390]) test(`간결한 브리핑과 선택일 누적·복사 문구 ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});
 await page.addInitScript(()=>{window.__briefingText='';Object.defineProperty(navigator,'share',{value:async({text})=>{window.__briefingText=text;},configurable:true});});
 await page.clock.setFixedTime(new Date('2026-09-19T03:00:00Z'));
 const id='00000000-0000-4000-8000-000000000001',store='광정동_산본점';
 const day=(sim,second,smart,bundle)=>{const matrix=Array.from({length:8},()=>[0,0,0,0,0,0]);matrix[5][0]=sim;matrix[7][0]=second;return {matrix,groups:{homeFlat:{smartHome:smart},bundle2nd:{b_AppleWatch:bundle}}};};
 await page.route('https://placeholder.supabase.co/**',async route=>{
  const table=new URL(route.request().url()).pathname.split('/').pop();
  if(table==='profiles')return route.fulfill({json:[{id,name:'집계직원',store_name:store,position:'사원',role:'employee',active:true,hire_date:'2026-01-01'},{id:'a50a0979-acef-40b1-98b7-f05074f1c835',name:'조회관리자',store_name:'운영진',position:'대표',role:'admin',active:true}]});
  if(table==='daily_records')return route.fulfill({json:[[17,day(2,1,0,1)],[18,day(3,1,1,2)],[19,day(9,8,2,4)]].map(([d,data])=>({user_id:id,work_date:`2026-09-${d}`,data}))});
  if(table==='store_goals')return route.fulfill({json:[{store_name:store,company_goals:{},challenge_goals:{hs:0,home:0,sono:0,second:10,simMnp:12,tvFree:0,free:0,smartHome:6,productivity:0,kpi:0,tailoredCount:0,tailored:0,tailoredAmount:0}}]});
  return route.fulfill({json:[]});
 });
 await page.addLocatorHandler(page.getByRole('button',{name:'좋아요!',exact:true}),b=>b.click());
 await page.goto('/tests/ui/calendar.html?actor=admin');
 await page.getByRole('button',{name:'관리자',exact:true}).click();
 await page.getByRole('button',{name:'일일 브리핑',exact:true}).click();
 const sim=page.getByTestId('briefing-metric-simMnp');
 const second=page.getByTestId('briefing-metric-second');
 const smart=page.getByTestId('briefing-metric-smart');
 await expect(sim).toContainText('목표 12건 · 실적 5건 · 달성 41.7%');
 await expect(sim).toContainText('진척 대비 18.3%p 부족');
 await expect(second).toContainText('목표 10건 · 실적 5건 · 달성 50%');
 await expect(smart).toContainText('목표 6건 · 실적 1건 · 달성 16.7%');
 await expect(page.getByTestId('briefing-metrics')).not.toContainText('예상');
 await page.getByRole('button',{name:'카카오 전달',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>window.__briefingText)).toContain('SIM MNP | 목표 12건 · 실적 5건 · 달성 41.7% | 진척 대비 18.3%p 부족');
 const daySelect=page.locator('select').filter({has:page.locator('option[value="18"]')});
 await daySelect.selectOption('17');
 await expect(sim).toContainText('목표 12건 · 실적 2건 · 달성 16.7%');
 await expect(sim).toContainText('진척 대비 40%p 부족');
 await expect(second).toContainText('목표 10건 · 실적 2건 · 달성 20%');
 await expect(smart).toContainText('목표 6건 · 실적 0건 · 달성 0%');
 await expect(page.getByTestId('briefing-metric-hs')).toContainText('목표 미설정');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:`/tmp/miso-briefing-${width}.png`,fullPage:true});
});
