import React from 'react';
import {createRoot} from 'react-dom/client';
import App from '../../src/App';
import '../../src/index.css';
const actor=new URLSearchParams(location.search).get('actor');
const isAdmin=actor==='admin';
const isArea=actor==='area',isManager=actor==='manager';
const id=isAdmin?'a50a0979-acef-40b1-98b7-f05074f1c835':isArea?'471280af-a046-4d25-a27d-63a0c5978403':'00000000-0000-4000-8000-000000000001';
localStorage.setItem(`miso_quick_guide_v1:${id}`,'seen');
createRoot(document.getElementById('root')).render(<App authUser={{id,email:'calendar@example.test'}} authProfile={{id,name:'캘린더검증',store_name:'대야동_롯데마트점',position:isAdmin?'대표':isArea?'담당':isManager?'점장':'사원',role:isAdmin?'admin':isArea||isManager?'manager':'employee',active:true,status:'approved'}} onSignOut={()=>{}}/>);
