begin;

create or replace function public.is_permission_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.id = 'a50a0979-acef-40b1-98b7-f05074f1c835'::uuid
      and p.name = '이강진'
      and p.role in ('admin', 'super_admin')
      and p.active = true
      and p.status = 'approved'
  );
$$;

revoke all on function public.is_permission_admin() from public, anon;
grant execute on function public.is_permission_admin() to authenticated;

create table if not exists public.profile_role_audit (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  old_role text,
  new_role text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists profile_role_audit_profile_id_idx
  on public.profile_role_audit(profile_id);
create index if not exists profile_role_audit_changed_by_idx
  on public.profile_role_audit(changed_by);

alter table public.profile_role_audit enable row level security;
grant select on public.profile_role_audit to authenticated;

drop policy if exists profile_role_audit_permission_admin_read on public.profile_role_audit;
create policy profile_role_audit_permission_admin_read
on public.profile_role_audit
for select
to authenticated
using ((select public.is_permission_admin()));

create or replace function public.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    new.role := old.role;
    new.status := old.status;
    new.active := old.active;
    new.name := old.name;
    new.employee_code := old.employee_code;
    new.store_name := old.store_name;
    new.position := old.position;
    new.hire_date := old.hire_date;
  elsif not public.is_permission_admin() then
    new.role := old.role;
  end if;
  return new;
end;
$$;

create or replace function public.audit_profile_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profile_role_audit(profile_id, old_role, new_role, changed_by)
  values (new.id, old.role, new.role, auth.uid());
  return new;
end;
$$;

revoke all on function public.audit_profile_role_change() from public, anon, authenticated;

drop trigger if exists profiles_role_audit on public.profiles;
create trigger profiles_role_audit
after update of role on public.profiles
for each row
when (old.role is distinct from new.role)
execute function public.audit_profile_role_change();

update public.app_config
set value = '[]'::jsonb
where config_key = 'auto_manager_positions';

comment on table public.profile_role_audit is
  'Records employee system role changes. Only the designated permission administrator can read it.';

commit;
