-- Privacy-safe product usage events. No customer, sale, amount, memo, or free-text data.
create table if not exists public.app_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('screen_view','feature_use')),
  role text not null check (role in ('employee','manager')),
  screen_key text not null check (char_length(screen_key) between 1 and 80),
  feature_key text check (feature_key is null or char_length(feature_key) between 1 and 80),
  app_version text,
  occurred_at timestamptz not null default now()
);

alter table public.app_usage_events enable row level security;

revoke all on table public.app_usage_events from anon;
grant insert on table public.app_usage_events to authenticated;
grant usage, select on sequence public.app_usage_events_id_seq to authenticated;

drop policy if exists app_usage_events_insert_own on public.app_usage_events;
create policy app_usage_events_insert_own
on public.app_usage_events
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create index if not exists app_usage_events_user_time_idx
  on public.app_usage_events (user_id, occurred_at desc);
create index if not exists app_usage_events_screen_time_idx
  on public.app_usage_events (screen_key, occurred_at desc);

comment on table public.app_usage_events is
  'Privacy-safe screen and feature usage telemetry. Never store customer or sale content.';
