-- Miso Pay web push subscriptions, delivery hook, and 09:00 KST customer-task reminders.
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
revoke all on public.push_subscriptions from anon;

drop policy if exists push_subscriptions_read_own on public.push_subscriptions;
create policy push_subscriptions_read_own on public.push_subscriptions for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists push_subscriptions_insert_own on public.push_subscriptions;
create policy push_subscriptions_insert_own on public.push_subscriptions for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists push_subscriptions_update_own on public.push_subscriptions;
create policy push_subscriptions_update_own on public.push_subscriptions for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists push_subscriptions_delete_own on public.push_subscriptions;
create policy push_subscriptions_delete_own on public.push_subscriptions for delete to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.push_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);
alter table public.push_config enable row level security;
revoke all on public.push_config from anon, authenticated;

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  notification_id bigint references public.notifications(id) on delete set null,
  recipient_id uuid references public.profiles(id) on delete cascade,
  endpoint_hash text,
  status text not null,
  detail text,
  created_at timestamptz not null default now()
);
alter table public.push_delivery_log enable row level security;
revoke all on public.push_delivery_log from anon, authenticated;

create table if not exists public.customer_task_reminders (
  task_id uuid not null references public.customer_tasks(id) on delete cascade,
  reminder_date date not null,
  notification_id bigint references public.notifications(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (task_id, reminder_date)
);
alter table public.customer_task_reminders enable row level security;
revoke all on public.customer_task_reminders from anon, authenticated;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.dispatch_push_notification()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare hook_secret text;
begin
  select value into hook_secret from public.push_config where key = 'hook_secret';
  if hook_secret is not null then
    perform net.http_post(
      url := 'https://ufkxbrzcmncwynvygaak.supabase.co/functions/v1/send-web-push',
      headers := jsonb_build_object('Content-Type','application/json','x-push-hook',hook_secret),
      body := jsonb_build_object('notification_id',new.id),
      timeout_milliseconds := 5000
    );
  end if;
  return new;
end;
$$;
revoke all on function private.dispatch_push_notification() from public, anon, authenticated;

drop trigger if exists notifications_dispatch_web_push on public.notifications;
create trigger notifications_dispatch_web_push
after insert on public.notifications
for each row execute function private.dispatch_push_notification();

create or replace function private.create_due_customer_task_notifications()
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare inserted_count integer;
begin
  with due as (
    select t.id, t.user_id, t.title, t.due_date, c.customer_name
    from public.customer_tasks t
    left join public.customers c on c.id = t.customer_id
    where t.status = 'pending'
      and t.due_date = (now() at time zone 'Asia/Seoul')::date
  ), inserted_reminders as (
    insert into public.customer_task_reminders(task_id, reminder_date)
    select id, due_date from due
    on conflict do nothing
    returning task_id
  ), made as (
    insert into public.notifications(recipient_id, actor_id, type, title, message, payload)
    select d.user_id, null, 'customer_task_due', '오늘 고객 약속이 있어요',
           concat(coalesce(d.customer_name,'고객'), ' · ', d.title),
           jsonb_build_object('task_id',d.id,'screen','customer','filter','today')
    from due d join inserted_reminders r on r.task_id = d.id
    returning id, (payload->>'task_id')::uuid as task_id
  )
  update public.customer_task_reminders r set notification_id = m.id
  from made m where r.task_id = m.task_id and r.reminder_date = (now() at time zone 'Asia/Seoul')::date;
  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;
revoke all on function private.create_due_customer_task_notifications() from public, anon, authenticated;

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'miso-due-customer-task-push';
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
  perform cron.schedule('miso-due-customer-task-push', '0 0 * * *', 'select private.create_due_customer_task_notifications();');
end $$;

-- Operational VAPID and hook secrets are provisioned directly in the protected
-- push_config table during deployment and are intentionally not committed.
